var enums = require('./core/enum.js'); //Contants used across he app

/*
 * Important configuation variables - minFolder, build
*/
var minFolder = 'minified'; //Target folder here your output file will be written
var build = enums.MIN_BUILD.BUILD; //Change this to 'enums.MIN_BUILD.DEBUG' to debug the Output file generated

var uglify = require("uglify-js"),      
      scha = require("./core/scha.js"),
      fs = require('fs'),
      fsWrite = function(dest, data, encoding){
        return new Promise(function(resolve, reject){
          fs.writeFile(dest, data, encoding || "utf8", function(err){
            if(err) {reject(err, dest)} else {resolve(dest)}
          });
        });
      };

  try {
    fs.mkdirSync(minFolder);
  } catch(e) {
    if ( e.code != 'EEXIST' ) throw e;
  }
     
  //Protection.js
  fsWrite("./"+minFolder+"/protection.min.js", (function(){
    // Simple closure function , since i didnt want to referece code variable
    var code = uglify.minify("./core/protection.js").code;
    return code.substring(0, code.length - 1); /*this is to remove the trailing semicolon generated by uglify*/
  })())
  .then(function(file){
    console.log("File processed:".green+file);  
  })
  .catch(function(err, dest){
    console.log("Unable to write file:".red + dest +"\nException:"+err);
  });

  //Unpacker.v2.js - New Browsers
  // fsWrite("./minified/unpacker.v2.min.js", jsfuck.encode((uglify.minify("./core/unpacker.v2.js")).code))
  var code = build === enums.MIN_BUILD.DEBUG ? '(function(n, i, r, u, s) {' + fs.readFileSync('./core/unpacker.v2.1.js') + '\n})' : scha((uglify.minify("./core/unpacker.v2.1.js")).code)
  fsWrite("./"+minFolder+"/unpacker.v2.min.js",code)
  .then(function(file){
    console.log("File processed:".green+file);  
  })
  .catch(function(err, dest){
    console.log("Unable to write file:".red + dest +"\nException:"+err);
  });
  
  //Unpacker.js - Old browser ie 9
  //fsWrite("./minified/unpacker.min.js", jsfuck.encode((uglify.minify("./core/unpacker.js")).code))
  fsWrite("./"+minFolder+"/unpacker.min.js", scha((uglify.minify("./core/unpacker.js")).code))
  .then(function(file){
    console.log("File processed:".green + file);  
  })
  .catch(function(err, dest){
    console.log("Unable to write file:".red + dest +"\nException:"+err);
  });